Repository kubernetes/enhancements, pull requests merged in 2018-06, with the labels that each got.

#570 SECURITY_CONTACTS added
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#572 Clarify features repo issue is required
  EXCEPTIONS.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#573 Add `features-maintainers` section to OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#577 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/M
