Repository kubernetes/enhancements, pull requests merged in 2018-07, with the labels that each got.

#582 Fixed Broken Links
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#584 Remove references to `kubernetes-pm`
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/XS

#602 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#605 Typo fix: Spreadhsheets->Spreadsheets
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
